CREATE CONSTRAINT tool_id IF NOT EXISTS
FOR (t:Tool)
REQUIRE t.id IS UNIQUE;

CREATE CONSTRAINT capability_id IF NOT EXISTS
FOR (c:Capability)
REQUIRE c.id IS UNIQUE;

CREATE CONSTRAINT domain_id IF NOT EXISTS
FOR (d:Domain)
REQUIRE d.id IS UNIQUE;

CREATE CONSTRAINT integration_id IF NOT EXISTS
FOR (i:Integration)
REQUIRE i.id IS UNIQUE;